<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1587588187513' stop='1587588223050'>
    <name>Jetpack connection</name>
    <title>Jetpack connection</title>
    <test-cases>
        <test-case start='1587588196021' status='failed' stop='1587588206070'>
            <name>Can find connect button on plugins page</name>
            <title>Can find connect button on plugins page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Test failed: Jetpack connection :: Can find connect button on plugins page' source='f2a74350-95db-42b3-a33f-7c48ba6bf776-attachment.png' type='image/png' size='107358'/>
            </attachments>
            <failure>
                <message>Error: expect(received).toBeTruthy()
                
                Received: false</message>
                <stack-trace>Error: expect(received).toBeTruthy()
                
                Received: false
                    at toBeTruthy (/home/travis/build/Automattic/jetpack/tests/e2e/specs/connection.test.js:26:56)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1587588206070' status='failed' stop='1587588214542'>
            <name>Can find connect button on dashboard page</name>
            <title>Can find connect button on dashboard page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Test failed: Jetpack connection :: Can find connect button on dashboard page' source='85377297-fa12-4a5f-b526-9998e936a92c-attachment.png' type='image/png' size='276229'/>
            </attachments>
            <failure>
                <message>Error: expect(received).toBeTruthy()
                
                Received: false</message>
                <stack-trace>Error: expect(received).toBeTruthy()
                
                Received: false
                    at toBeTruthy (/home/travis/build/Automattic/jetpack/tests/e2e/specs/connection.test.js:33:54)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1587588214542' status='failed' stop='1587588223050'>
            <name>Can find connect button on Jetpack page</name>
            <title>Can find connect button on Jetpack page</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Test failed: Jetpack connection :: Can find connect button on Jetpack page' source='1858dbdc-647e-45bb-9c5a-b20f939c6960-attachment.png' type='image/png' size='116162'/>
            </attachments>
            <failure>
                <message>Error: expect(received).toBeTruthy()
                
                Received: false</message>
                <stack-trace>Error: expect(received).toBeTruthy()
                
                Received: false
                    at toBeTruthy (/home/travis/build/Automattic/jetpack/tests/e2e/specs/connection.test.js:40:56)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>